bridge = "huawei"
port = 12350
username = "AA:AA:AA:AA:AA:11"

[[services]]
type = "AccessoryInformation"

[services.characteristics]
Identify = {} # leave property completely out 'cos otherwise Homekit won't accept
Manufacturer = "Jyri-Matti Lähteenmäki"
Model = "SUN2000"
Name = "Huawei"
SerialNumber = "AA:AA:AA:AA:AA:11"
FirmwareRevision = "100.1.1"


[[services]]
type = "TemperatureSensor"

[services.characteristics]
Name = "Total active power"
ConfiguredName = "Total active power"
[services.characteristics.CurrentTemperature]
minValue = -99
maxValue = 99999
cmd = "cd huawei; ./cmd/total_active_power.sh"


[[services]]
type = "TemperatureSensor"

[services.characteristics]
Name = "Total yield"
ConfiguredName = "Total yield"
[services.characteristics.CurrentTemperature]
minValue = -99
maxValue = 99999999
cmd = "cd huawei; ./cmd/total_yield.sh"
