bridge = "huawei"
port = 12311
username = "AA:AA:AA:AA:AA:11"

[[services]]
type = "AccessoryInformation"

[services.characteristics]
Identify = {} # leave property completely out 'cos otherwise Homekit won't accept
Manufacturer = "Jyri-Matti Lähteenmäki"
Model = "SUN2000"
Name = "Huawei"
SerialNumber = "AA:AA:AA:AA:AA:11"
FirmwareRevision = "100.1.1"


[[services]]
type = "TemperatureSensor"

[services.characteristics]
Name = "Total active power"
ConfiguredName = "Total active power"
[services.characteristics.CurrentTemperature]
minValue = -99
maxValue = 99999
cmd = "cd huawei; ./cmd/total_active_power.sh"


[[services]]
type = "TemperatureSensor"

[services.characteristics]
Name = "Total yield"
ConfiguredName = "Total yield"
[services.characteristics.CurrentTemperature]
minValue = -99
maxValue = 99999999
cmd = "cd huawei; ./cmd/total_yield.sh"


[[services]]
type = "TemperatureSensor"

[services.characteristics]
Name = "Kuluvan tunnin energia"
ConfiguredName = "Kuluvan tunnin energia"
[services.characteristics.CurrentTemperature]
minValue = -99999
maxValue = 99999
minStep = 0.001
cmd = "cd huawei; ./cmd/current_hourly_yield.sh ./huawei.db"


[[services]]
type = "TemperatureSensor"

[services.characteristics]
Name = "Kuluvan vartin energia"
ConfiguredName = "Kuluvan vartin energia"
[services.characteristics.CurrentTemperature]
minValue = -99999
maxValue = 99999
minStep = 0.001
cmd = "cd huawei; ./cmd/current_quarterly_yield.sh ./huawei.db"


[[services]]
type = "TemperatureSensor"

[services.characteristics]
Name = "Edeltävän tunnin energia"
ConfiguredName = "Edeltävän tunnin energia"
[services.characteristics.CurrentTemperature]
minValue = -99999
maxValue = 99999
minStep = 0.001
cmd = "cd huawei; ./cmd/previous_hourly_yield.sh ./huawei.db"


[[services]]
type = "TemperatureSensor"

[services.characteristics]
Name = "Edeltävän vartin energia"
ConfiguredName = "Edeltävän vartin energia"
[services.characteristics.CurrentTemperature]
minValue = -99999
maxValue = 99999
minStep = 0.001
cmd = "cd huawei; ./cmd/previous_quarterly_yield.sh ./huawei.db"
